# coding: utf-8

import numpy as np,scipy as sp,scipy.signal as ss,pyfftw as fftw,rmwarp,rmwarp.framer
r=rmwarp.RMFFT(win=ss.hann(2048,sym=True));f = rmwarp.framer.NpFramer('/home/zen/Music/Chase & Status - Loader-8XsojGZ8tps.mp3',frame_size=r.size,hop_size=16,layout='mono');
f.seek(32.)
f.next_pts
f.s.time_base
f.s.time_base * f.next_pts
float(f.s.time_base * f.next_pts)
F=next(_ for _ in f if _.std() >= 0.2)
spec = list(r.process(next(f)) for i in range(16))
spec[0]
get_ipython().magic('pylab')
plt.plot(np.diff(spec[1].M));plt.plot(spec[1].dM_dw/f.frame_size)
plt.plot(np.diff(spec[2].M));plt.plot(spec[2].dM_dw/f.frame_size)
plt.plot(np.diff(spec[3].M)+3);plt.plot(spec[3].dM_dw/f.frame_size+3)
plt.clf()
plt.plot(np.diff(spec[2].M)/(spec[2].dM_dw/f.frame_size))
plt.plot(np.diff(spec[2].M)/(spec[2].dM_dw/f.frame_size)[:-1])
plt.plot(np.diff(spec[2].M)/(spec[2].dM_dw/f.frame_size)[1:])
plt.clf()
plt.plot((spec[2].M[1:] - spec[2].M[:-1])*0.5);plt.plot((spec[2].dM_dw/f.frame_size)[1:-1])
plt.plot((spec[3].M[1:] - spec[3].M[:-1])*0.5);plt.plot((spec[3].dM_dw/f.frame_size)[1:-1])
plt.plot(spec[7].dM_dt*f.hop_size)
plt.plot(spec[7].M - spec[6].M)
plt.plot(spec[7].M - spec[8].M)
plt.plot(spec[7].M - spec[8].M + 0.5
)
plt.plot((spec[7].dM_dt+spec[8].dM_dt) * 0.5 *f.hop_size)
plt.plot((spec[7].dM_dt+spec[8].dM_dt) * 0.5 *f.hop_size + 0.5)
plt.plot(-(spec[7].dM_dt+spec[8].dM_dt) * 0.5 *f.hop_size + 0.5)
plt.clf()
plt.plot((spec[7].dM_dt+spec[8].dM_dt) * 0.5 *f.hop_size + 0.5)
plt.plot(spec[8].M - spec[7].M + 0.5)
plt.plot(spec[7].M - spec[6].M )
plt.plot((spec[5].dM_dt+spec[7].dM_dt) * 0.5 *f.hop_size)
plt.clf()
plt.plot(spec[5].dPhi_dt * f.hop_size)
r = rmwarp.RMFFT(win=ss.kaiser(2048,24.));f=rmwarp.framer.NpFramer('/home/zen/.test.mp4',frame_size=2048,hop_size=8,layout='mono')
f.seek(32.)
F=next(_ for _ in f if _.std() >= 0.2)
f.seek(64.)
F=next(_ for _ in f if _.std() >= 0.2)
spec = list(r.process(next(f)) for i in range(16))
plt.clf()
plt.plot(spec[5].dPhi_dt * f.hop_size)
plt.plot(spec[5].Phi - spec[4].Phi )
plt.plot((spec[5].Phi - spec[4].Phi )/f.frame_size)
plt.clf()
plt.plot((spec[5].Phi - spec[4].Phi )/f.frame_size)
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5)
unit = np.arange(r.coef) * (2 * np.pi / r.size)
plt.plot((spec[5].Phi - unit) - (spec[4].Phi - unit) )/f.frame_size)
plt.plot((spec[5].Phi - unit) - (spec[4].Phi - unit)/f.frame_size))
plt.plot((spec[5].Phi - unit) - (spec[4].Phi - unit)/f.frame_size)
plt.clf()
unit.max()
f.hop_size
plt.plot(spec[5].dPhi_dt - unit * f.hop_size)
plt.clf()
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5)
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 + unit)
plt.clf()
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 + unit)
plt.clf()
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 + unit/f.frame_size)
plt.clf()
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 + unit/2)
r = rmwarp.RMFFT(win=ss.kaiser(2048,64.));f=rmwarp.framer.NpFramer('/home/zen/.test.mp4',frame_size=2048,hop_size=8,layout='mono')
f.seek(64.)
F=next(_ for _ in f if _.std() >= 0.2)
spec = list(r.process(next(f)) for i in range(16))
plt.clf()
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 + unit/2)
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 + unit)
plt.clf()
plt.plot((spec[5].Phi-spec[4].Phi )/f.frame_size - unit)
plt.clf()
plt.plot((spec[5].Phi-spec[4].Phi )/f.frame_size + unit)
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 + unit)
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 + unit * 0.5)
plt.plot((spec[5].Phi-spec[4].Phi )/f.frame_size + unit*0.5)
plt.clf()
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 + unit * 0.5)
plt.plot((spec[5].Phi-spec[4].Phi )/f.frame_size + unit*0.5)
plt.plot((spec[5].Phi-spec[4].Phi )/f.frame_size )
plt.clf()
plt.plot((spec[5].Phi-spec[4].Phi )/f.frame_size )
plt.plot((spec[5].Phi-spec[4].Phi )/f.frame_size - unit/2)
plt.clf()
plt.plot((spec[5].Phi-spec[4].Phi )/f.frame_size/f.hop_size)
plt.clf()
plt.plot((spec[5].Phi-spec[4].Phi )/f.hop_size - unit)
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 )
plt.plot(np.remainder((spec[5].Phi-spec[4].Phi )/f.hop_size - unit,np.pi/4))
plt.plot(np.remainder((spec[5].Phi-spec[4].Phi )/f.hop_size - unit,np.pi/8))
def princarg(x):
    return np.remainder(x,np.pi * 2)
plt.plot(princarg(spec[5].Phi-spec[4].Phi )/f.hop_size - unit)
plt.clf()
plt.plot(princarg(spec[5].Phi-spec[4].Phi )/f.hop_size - unit)
plt.plot(princarg(princarg(spec[5].Phi-spec[4].Phi )/f.hop_size - unit))
plt.clf()
plt.plot(princarg(spec[5].Phi-spec[4].Phi )/f.hop_size - unit)
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 )
plt.plot(remainder(princarg(spec[5].Phi-spec[4].Phi )/f.hop_size - unit,np.pi/2))
plt.plot(np.remainder(princarg(spec[5].Phi-spec[4].Phi )/f.hop_size - unit,np.pi/2))
plt.clf()
plt.plot(np.remainder(princarg(spec[5].Phi-spec[4].Phi )/f.hop_size - unit + np.pi/4,np.pi/2))
plt.clf()
plt.plot(np.remainder(princarg(spec[5].Phi-spec[4].Phi )/f.hop_size - unit + np.pi/4,np.pi))
plt.clf()
plt.plot(princarg(spec[5].Phi-spec[4].Phi + np.pi )/f.hop_size - unit))
plt.plot(princarg(spec[5].Phi-spec[4].Phi + np.pi )/f.hop_size - unit)
plt.clf()
plt.plot(princarg(spec[5].Phi-spec[4].Phi) - unit * f.hop_size)
plt.plot(princarg(spec[5].Phi-spec[4].Phi)/f.hop_size - unit )
np.pi/4
plt.plot(np.fmod((princarg(spec[5].Phi-spec[4].Phi)/f.hop_size - unit) - np.pi/16, np.pi/4))
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 )
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 - np.pi/4)
plt.clf()
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 - np.pi/8)
plt.plot(np.fmod((princarg(spec[5].Phi-spec[4].Phi)/f.hop_size - unit) - np.pi/16, np.pi/4))
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 + np.pi/8)
plt.clf()
plt.plot(np.fmod((princarg(spec[5].Phi-spec[4].Phi)/f.hop_size - unit) - np.pi/16, np.pi/4))
plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 -np.pi/16
)
#plt.plot((spec[5].dPhi_dt + spec[4].dPhi_dt)*0.5 -np.pi/16)
plt.plot(np.fmod((princarg(spec[5].Phi-spec[4].Phi)/f.hop_size - unit) - np.pi/16, np.pi/4))
diffs = lambda n: plt.plot(np.fmod((princarg(spec[n].Phi-spec[n-1].Phi)/f.hop_size - unit) - np.pi/16, np.pi/4)) + n
diffs(0)
diffs = lambda n: plt.plot(np.fmod((princarg(spec[n].Phi-spec[n-1].Phi)/f.hop_size - unit) - np.pi/16, np.pi/4) + n)
plt.clf()
diffs(0),diffs(1),diffs(2)
plt.clf()
diffs(1),diffs(2),diffs(3)
sames = lambda n:plt.plot((spec[n].dPhi_dt + spec[n-1].dPhi_dt)*0.5 -np.pi/16+n)
sames(1),sames(2),sames(3)
sames = lambda n:plt.plot((spec[n].dPhi_dt + spec[n-1].dPhi_dt)*0.5 -np.pi/16+n/4)
diffs = lambda n: plt.plot(np.fmod((princarg(spec[n].Phi-spec[n-1].Phi)/f.hop_size - unit) - np.pi/16, np.pi/4) + n/4)
plt.clf()
map((lambda x:diffs(x),sames(x)),range(1,8))
map((lambda x:(diffs(x),sames(x))),range(1,8))
listmap((lambda x:(diffs(x),sames(x))),range(1,8))
list(map((lambda x:(diffs(x),sames(x))),range(1,8)))
plt.clf()
r=rmwarp.RMFFT(win=ss.hann(2048,sym=True));f = rmwarp.framer.NpFramer('/home/zen/Music/Chase & Status - Loader-8XsojGZ8tps.mp3',frame_size=r.size,hop_size=128,layout='mono');
f.seek(64.)
F=next(_ for _ in f if _.std() >= 0.2)
spec = list(r.process(next(f)) for i in range(16))
spec = list(r.process(next(f)) for i in range(16))
diffs = lambda n: plt.plot(np.fmod((princarg(spec[n].Phi-spec[n-1].Phi)/f.hop_size - unit) - np.pi/16, np.pi/4) + n/4)
sames = lambda n:plt.plot((spec[n].dPhi_dt + spec[n-1].dPhi_dt)*0.5 -np.pi/16+n/4)
list(map((lambda x:(diffs(x),sames(x))),range(1,8)))
diffs = lambda n: plt.plot(np.fmod((princarg(spec[n].Phi-spec[n-1].Phi)/f.hop_size - unit) - np.pi/(2 * f.hop_size), np.pi/(f.hop_size/2)) + n/4)
list(map((lambda x:(diffs(x),sames(x))),range(1,8)))
plt.clf()
list(map((lambda x:(diffs(x),sames(x))),range(1,8)))
sames = lambda n:plt.plot((spec[n].dPhi_dt + spec[n-1].dPhi_dt)*0.5 -np.pi/(2 * f.hop_size)+n/4)
list(map((lambda x:(diffs(x),sames(x))),range(1,8)))
plt.clf()
list(map((lambda x:(diffs(x),sames(x))),range(1,8)))
plt.clf()
sames = lambda n:plt.plot((spec[n].dPhi_dt + spec[n-1].dPhi_dt)*0.5 -np.pi/(2 * f.hop_size)+n/f.hop_size)
diffs = lambda n: plt.plot(np.fmod((princarg(spec[n].Phi-spec[n-1].Phi)/f.hop_size - unit) - np.pi/(2 * f.hop_size), np.pi/(f.hop_size/2)) + n/f.hop_size)
list(map((lambda x:(diffs(x),sames(x))),range(1,8)))
plt.clf()
diffs = lambda n: plt.plot(np.fmod((princarg(spec[n].Phi-spec[n-1].Phi)/f.hop_size - unit) - np.pi/(2 * f.hop_size), np.pi/(f.hop_size/2)) + n * 4/f.hop_size)
sames = lambda n:plt.plot(-(spec[n].dPhi_dt + spec[n-1].dPhi_dt)*0.5 -np.pi/(2 * f.hop_size)+n* 4/f.hop_size)
list(map((lambda x:(diffs(x),sames(x))),range(1,8)))
sames = lambda n:plt.plot(-(spec[n].dPhi_dt + spec[n-1].dPhi_dt)*0.5 -np.pi/(2 * f.hop_size)+(n+0.25)* 4/f.hop_size)
list(map((lambda x:(diffs(x),sames(x))),range(1,8)))
f.seek(128.)
r=rmwarp.RMFFT(win=ss.hann(2048,sym=True));f = rmwarp.framer.NpFramer('/home/zen/Music/Chase & Status - Loader-8XsojGZ8tps.mp3',frame_size=r.size,hop_size=256,layout='mono');
sames = lambda n:plt.plot(-(spec[n].dPhi_dt + spec[n-1].dPhi_dt)*0.5 -np.pi/(2 * f.hop_size)+(n+0.25)* 4/f.hop_size)
diffs = lambda n: plt.plot(np.fmod((princarg(spec[n].Phi-spec[n-1].Phi)/f.hop_size - unit) - np.pi/(2 * f.hop_size), np.pi/(f.hop_size/2)) + n * 4/f.hop_size)
spec = list(r.process(next(f)) for i in range(16))
f.seek(128.)
F=next(_ for _ in f if _.std() >= 0.2)
spec = list(r.process(next(f)) for i in range(16))
sames = lambda n:plt.plot(-(spec[n].dPhi_dt + spec[n-1].dPhi_dt)*0.5 -np.pi/(2 * f.hop_size)+(n+0.25)* 4/f.hop_size)
diffs = lambda n: plt.plot(np.fmod((princarg(spec[n].Phi-spec[n-1].Phi)/f.hop_size - unit) - np.pi/(2 * f.hop_size), np.pi/(f.hop_size/2)) + n * 4/f.hop_size)
list(map((lambda x:(diffs(x),sames(x))),range(1,8)))
plt.clf()
list(map((lambda x:(diffs(x),sames(x))),range(1,8)))
plt.plot(specs[0].dM_dw)
plt.plot(spec[0].dM_dw)
plt.clf()
plt.plot(spec[0].dPhi_dw)
np.diff(spec[2].Phi)
plt.clf()
sames = lambda n:plt.plot(-(spec[n].dPhi_dt + spec[n-1].dPhi_dt)*0.5 -np.pi/(2 * f.hop_size)+(n+0.25)* 4/f.hop_size)
diffs = lambda n: plt.plot(np.fmod((princarg(spec[n].Phi-spec[n-1].Phi)/f.hop_size - unit) - np.pi/(2 * f.hop_size), np.pi/(f.hop_size/2)) + n * 4/f.hop_size)
unit = np.arange(r.coef) * (2 * np.pi / r.size)
get_ipython().magic('history')
get_ipython().magic('pinfo %history')
get_ipython().magic('history -n')
get_ipython().magic('save ./rm_session.py 0-192')
plt.plot(spec[0].d2Phi_dtdw)
plt.plot(spec[0].dPhi_dw)
np.diff(spec[2].Phi)
deriv[1:] + deriv[:-1]/ sp.diff(win)
plt.plot((spec[3].M[1:] - spec[3].M[:-1])*0.5);plt.plot((spec[3].dM_dw/f.frame_size)[1:-1])
plt.clf()
plt.plot((spec[3].M[1:] - spec[3].M[:-1])*0.5);plt.plot((spec[3].dM_dw/f.frame_size)[1:-1])
plt.plot(princarg(spec[3].Phi[1:] - spec[3].Phi[:-1])*0.5);plt.plot((spec[3].dPhi_dw/f.frame_size)[1:-1])
plt.clf()
plt.plot(princarg(spec[3].Phi[1:] - spec[3].Phi[:-1])*0.5);plt.plot((spec[3].dPhi_dw/f.frame_size)[1:-1])
plt.plot((spec[3].Phi[1:] - spec[3].Phi[:-1])*0.5);plt.plot((spec[3].dPhi_dw/f.frame_size)[1:-1)

)
plt.clf()
plt.plot(spec[3].Phi[1:] - spec[3].Phi[:-1])*0.5);plt.plot((spec[3].dPhi_dw/f.frame_size)[1:-1)
plt.plot((spec[3].Phi[1:] - spec[3].Phi[:-1])*0.5);plt.plot((spec[3].dPhi_dw/f.frame_size)[1:-1)

)
plt.plot((spec[3].Phi[1:] - spec[3].Phi[:-1])*0.5);plt.plot((spec[3].dPhi_dw/f.frame_size)[1:-1])
plt.plot(princarg(spec[3].Phi[1:] - spec[3].Phi[:-1])*0.5);plt.plot((spec[3].dPhi_dw/f.frame_size)[1:-1])
plt.clf()
plt.plot(princarg(spec[3].Phi[1:] - spec[3].Phi[:-1]));plt.plot((spec[3].dPhi_dw/f.frame_size)[1:-1])
plt.plot(princarg(spec[3].Phi[1:] - spec[3].Phi[:-1])*0.5);plt.plot((spec[3].dPhi_dw)[1:-1])
plt.plot(princarg(spec[3].Phi[1:] - spec[3].Phi[:-1]));plt.plot((spec[3].dPhi_dw/f.frame_size)[1:-1])
plt.clf()
plt.plot(princarg(spec[3].Phi[1:] - spec[3].Phi[:-1]));plt.plot((spec[3].dPhi_dw/f.frame_size)[1:-1])
plt.plot(princarg(spec[3].Phi[1:] - spec[3].Phi[:-1]));plt.plot((spec[3].dPhi_dw*2*np.pi/f.frame_size)[1:-1])
plt.clf()
plt.clf()
plt.plot(princarg(spec[3].Phi[1:] - spec[3].Phi[:-1]));plt.plot((spec[3].dPhi_dw*2*np.pi/f.frame_size)[1:-1])
plt.plot(-princarg(spec[3].Phi[1:] - spec[3].Phi[:-1]));plt.plot((spec[3].dPhi_dw*2*np.pi/f.frame_size)[1:-1])
plt.clf()
plt.clf()
plt.plot(-princarg(spec[3].Phi[1:] - spec[3].Phi[:-1]));plt.plot((spec[3].dPhi_dw*2*np.pi/f.frame_size)[1:-1])
plt.plot(-princarg(spec[3].Phi[1:] - spec[3].Phi[:-1]));plt.plot((spec[3].dPhi_dw*2*np.pi/f.frame_size)[1:-1])
plt.clf()
plt.plot(-princarg(spec[3].Phi[1:] - spec[3].Phi[:-1]));plt.plot((spec[3].dPhi_dw*2*np.pi/f.frame_size)[1:-1])
plt.plot(-princarg(spec[3].Phi[1:] - spec[3].Phi[:-1]) - (spec[3].dPhi_dw*2*np.pi/f.frame_size)[1:-1])
plt.plot(-princarg(spec[3].Phi[1:] - spec[3].Phi[:-1]) - (spec[3].dPhi_dw*2*np.pi/f.frame_size)[1:])
plt.clf()
plt.plot(-princarg(spec[3].Phi[1:] - spec[3].Phi[:-1]) - (spec[3].dPhi_dw*2*np.pi/f.frame_size)[1:])
plt.plot(-princarg(spec[3].Phi[1:] - spec[3].Phi[:-1])*0.5 - (spec[3].dPhi_dw*2*np.pi/f.frame_size)[1:])
plt.clf()
plt.plot(-princarg(spec[3].Phi[1:] - spec[3].Phi[:-1])*0.5 - (spec[3].dPhi_dw*2*np.pi/f.frame_size)[1:])
plt.plot(-princarg(spec[3].Phi[1:] - spec[3].Phi[:-1]));plt.plot((spec[3].dPhi_dw*2*np.pi/f.frame_size)[1:-1])
plt.clf()
plt.plot(-princarg(spec[4].Phi[1:] - spec[4].Phi[:-1]));plt.plot((spec[4].dPhi_dw*2*np.pi/f.frame_size)[1:-1])
plt.plot(-princarg(spec[4].Phi[1:] - spec[4].Phi[:-1]));plt.plot((spec[4].dPhi_dw*2*np.pi/f.frame_size)[1:-1] - np.pi)
plt.plot(-princarg(spec[4].Phi[1:] - spec[4].Phi[:-1] + np.pi));plt.plot((spec[4].dPhi_dw*2*np.pi/f.frame_size)[1:-1] 
)
plt.clf()
plt.plot(-princarg(spec[4].Phi[1:] - spec[4].Phi[:-1] + np.pi));plt.plot((spec[4].dPhi_dw*2*np.pi/f.frame_size)[1:-1] ))
plt.plot(-princarg(spec[4].Phi[1:] - spec[4].Phi[:-1] + np.pi));plt.plot((spec[4].dPhi_dw*2*np.pi/f.frame_size)[1:-1] )
plt.plot(-princarg(spec[4].Phi[1:] - spec[4].Phi[:-1] - np.pi)*0.5);plt.plot((spec[4].dPhi_dw*2*np.pi/f.frame_size)[1:-1] )
plt.plot(-princarg(spec[4].Phi[1:] - spec[4].Phi[:-1] + np.pi)*0.5);plt.plot((spec[4].dPhi_dw*2*np.pi/f.frame_size)[1:-1] )
plt.plot(-princarg(spec[4].Phi[1:] - spec[4].Phi[:-1])*0.5 + np.pi);plt.plot((spec[4].dPhi_dw*2*np.pi/f.frame_size)[1:-1] )
plt.clf()
plt.clf()
plt.plot(-princarg(spec[4].Phi[1:] - spec[4].Phi[:-1])*0.5 + np.pi);plt.plot((spec[4].dPhi_dw*2*np.pi/f.frame_size)[1:-1] )
plt.plot(-princarg(spec[4].Phi[1:] - spec[4].Phi[:-1]) + np.pi);plt.plot((spec[4].dPhi_dw*2*np.pi/f.frame_size)[1:-1] )
plt.clf()
plt.plot(-princarg(spec[4].Phi[1:] - spec[4].Phi[:-1]) + np.pi);plt.plot((spec[4].dPhi_dw*2*np.pi/f.frame_size)[1:-1] )
plt.plot(-princarg(spec[5].Phi[1:] - spec[5].Phi[:-1]) + np.pi);plt.plot((spec[5].dPhi_dw*2*np.pi/f.frame_size)[1:-1] )
plt.plot(-princarg(spec[5].Phi[1:] - spec[5].Phi[:-1])*f.frame_size/(2*m_pi) + np.pi);plt.plot((spec[5].dPhi_dw)[1:-1] )
plt.plot(-princarg(spec[5].Phi[1:] - spec[5].Phi[:-1])*f.frame_size/(2*np.pi) + np.pi);plt.plot((spec[5].dPhi_dw)[1:-1] )
plt.clf()
plt.plot(-princarg(spec[5].Phi[1:] - spec[5].Phi[:-1])*f.frame_size/(2*np.pi) + np.pi);plt.plot((spec[5].dPhi_dw)[1:-1] )
plt.plot(-princarg(spec[5].Phi[1:] - spec[5].Phi[:-1])*f.frame_size/(2*np.pi));plt.plot((spec[5].dPhi_dw)[1:-1] )
plt.clf()
plt.plot(-princarg(spec[5].Phi[1:] - spec[5].Phi[:-1])*f.frame_size/(2*np.pi));plt.plot((spec[5].dPhi_dw)[1:-1] )
plt.plot((-princarg(spec[5].Phi[1:] - spec[5].Phi[:-1])+ np.pi)f.frame_size/(2*np.pi));plt.plot((spec[5].dPhi_dw)[1:-1] )
plt.plot((-princarg(spec[5].Phi[1:] - spec[5].Phi[:-1])+ np.pi)*f.frame_size/(2*np.pi));plt.plot((spec[5].dPhi_dw)[1:-1] )
plt.clf()
plt.plot((-princarg(spec[5].Phi[1:] - spec[5].Phi[:-1])+ np.pi)*f.frame_size/(2*np.pi));plt.plot((spec[5].dPhi_dw)[1:-1] )
doit = lambda i: (plt.plot((-princarg(spec[i].Phi[1:] - spec[i].Phi[:-1])+ np.pi)*f.frame_size/(2*np.pi)),plt.plot((spec[i].dPhi_dw)[1:-1] ))
doit(0)
doit(1)
plt.clf()
doit = lambda i: (plt.plot((-princarg(spec[i].Phi[1:] - spec[i].Phi[:-1])+ np.pi)*f.frame_size/(2*np.pi) + f.frame_size*i),plt.plot((spec[i].dPhi_dw)[1:-1] +f.frame_size*i))
doit(1)
doit(2)
doit(3)
doit(4)
doit(8)
doit(9)
doit = lambda i: (plt.plot((-princarg(spec[i].Phi[1:] - spec[i].Phi[:-1])+ np.pi)*f.frame_size/(2*np.pi) + f.frame_size*0),plt.plot((spec[i].dPhi_dw)[1:-1] +f.frame_size*0))
plt.clf()
doit(0)
doit(4)
doit(8)
doit(12)
doit = lambda i: (plt.plot((-princarg(spec[i].Phi[1:] - spec[i].Phi[:-1])+ np.pi)*f.frame_size/(2*np.pi) + f.frame_size*i),plt.plot((spec[i].dPhi_dw)[1:-1] +f.frame_size*i))

"""
difference of phase w.r.t. frequency <-> dPhi_dw * 2 * np.pi / frame_size
"""
F=next(_ for _ in f if _.std() >= 0.2)
spec+=list(r.process(next(f)) for i in range(16))
spec.clear()
spec+=list(r.process(next(f)) for i in range(16))
list(map(doit,range(len(spec)))
)
plt.clf()
list(map(doit,range(len(spec)))
)
plt.plot(spec[0].d2Phi_dtdw)
plt.clf()
plt.plot(spec[0].d2Phi_dtdw)
spec[0].d2Phi_dtdw
spec[0].d2Phi_dtdw < 0.125
np.where(spec[0].d2Phi_dtdw < 0.125)
np.nonzero(spec[0].d2Phi_dtdw < 0.125)
np.nonzero(spec[0].d2Phi_dtdw < 0.00125)
np.nonzero(np.abs(spec[0].d2Phi_dtdw )< 0.00125)
np.nonzero(np.abs(spec[0].d2Phi_dtdw )< 0.125)
np.where(np.abs(spec[0].d2Phi_dtdw )< 0.125)
z=np.where(np.abs(spec[0].d2Phi_dtdw )< 0.125)
plt.plot(z,(spec[0].d2Phi_dtdw[_] for _ in z))
plt.plot(z,list(spec[0].d2Phi_dtdw[_] for _ in z))
z
plt.plot(z[0],list(spec[0].d2Phi_dtdw[_] for _ in z[0]))
plt.clf()
plt.plot(z[0],list(spec[0].d2Phi_dtdw[_] for _ in z[0]))
list(map(doit,range(len(spec))))
plt.clf()
plt.plot(z[0],list(spec[0].d2Phi_dtdw[_] for _ in z[0]))
plt.clf()
list(map(doit,range(len(spec))))
doit2 = lambda i:(plt.plot((spec[i].dPhi_dw) - spec[i-1].dPhi_dw +f.frame_size*i))
doit2
doit2(1)
plt.clf()
doit2(1)
doit2(2)
doit2(3)
doit2(4)
doit2 = lambda i:(plt.plot((spec[i].dPhi_dw) - spec[i-1].dPhi_dw +f.frame_size*i),plt.plot([f.frame_size * i]*r.coef))
doit2(1)
plt.clf()
doit2(1)
doit2(2)
doit2(3)
doit2(4)
doit2(5)
doit2 = lambda i:(plt.plot((spec[i].dPhi_dw) - spec[i-1].dPhi_dw +f.frame_size*i),plt.plot([f.frame_size * i]*r.coef)),plt.plot([f.hop_size + f.frame_size * i]*r.coef)
doit2 = lambda i:(plt.plot((spec[i].dPhi_dw) - spec[i-1].dPhi_dw +f.frame_size*i),plt.plot([f.frame_size * i]*r.coef),plt.plot([f.hop_size + f.frame_size * i]*r.coef))
doit2(4)
plt.clf()
doit2(4)
doit2(5)
doit2(6)
doit2(7)
plt.clf()
doit2 = lambda i:(plt.plot(((spec[i].dPhi_dw) - spec[i-1].dPhi_dw)/f.hop_size +f.frame_size*i),plt.plot([f.frame_size * i]*r.coef),plt.plot([f.hop_size + f.frame_size * i]*r.coef))
doit2(7)
doit2 = lambda i:(plt.plot(((spec[i].dPhi_dw) - spec[i-1].dPhi_dw)/f.hop_size +f.frame_size*i),plt.plot([f.frame_size * i]*r.coef),plt.plot([f.1 + f.frame_size * i]*r.coef))
doit2 = lambda i:(plt.plot(((spec[i].dPhi_dw) - spec[i-1].dPhi_dw)/f.hop_size +f.frame_size*i),plt.plot([f.frame_size * i]*r.coef),plt.plot([1 + f.frame_size * i]*r.coef))
plt.clf()
doit2(7)
doit2(6)
plt.clf()
doit2 = lambda i:(plt.plot(((spec[i].dPhi_dw) - spec[i-1].dPhi_dw) +f.frame_size*i),plt.plot([f.frame_size * i]*r.coef),plt.plot([f.hop_size + f.frame_size * i]*r.coef))
doit2(6)
F=next(_ for _ in f if _.std() >= 0.2)
spec.clear()
spec+=list(r.process(next(f)) for i in range(16))
list(map(doit2,range(1,len(spec))))
plt.clf()
spec+=list(r.process(next(f)) for i in range(64))
plt.plot(list(_.dPhi_dw[8] for _ in spec))
plt.plot(list(_.dPhi_dw[16] for _ in spec))
plt.plot(list(_.dPhi_dw[32] for _ in spec))
plt.plot(list(_.dPhi_dw[64] for _ in spec))
plt.plot(list(-_.dPhi_dw[64] for _ in spec))
plt.clf()
plt.plot(list(-_.dPhi_dw[64] for _ in spec))
plt.plot(np.asarraylist(-_.dPhi_dw[64] for _ in spec))
plt.plot(np.asarray(-_.dPhi_dw[64] for _ in spec))
plt.plot(np.fromiter(-_.dPhi_dw[64] for _ in spec))
plt.plot(np.fromiter((-_.dPhi_dw[64] for _ in spec),dtype=np.float32))
plt.clf()
plt.plot(np.fromiter((-_.dPhi_dw[64] for _ in spec),dtype=np.float32))
plt.plot(np.fromiter((-_.dPhi_dw[64] for _ in spec),dtype=np.float32)-np.arange(len(spec)*f.hop_size)
)
plt.plot(np.fromiter((-_.dPhi_dw[64] for _ in spec),dtype=np.float32)-np.arange(len(spec))*f.hop_size)
plt.clf()
plt.plot(np.fromiter((-_.dPhi_dw[64] for _ in spec),dtype=np.float32)-np.arange(len(spec))*f.hop_size)
plt.clf()
list(map(doit2,range(1,len(spec))))
plt.plot(np.fromiter((-_.dPhi_dw[64] for _ in spec),dtype=np.float32)-np.arange(len(spec))*f.hop_size * f.frame_size/2/np.pi)
plt.clf()
plt.plot(np.fromiter((-_.dPhi_dw[64] for _ in spec),dtype=np.float32)-np.arange(len(spec))*f.hop_size * f.frame_size/2/np.pi)
plt.plot(np.fromiter((-_.dPhi_dw[64] for _ in spec),dtype=np.float32)-np.arange(len(spec))*f.hop_size *2 * np.pi / f.frame_size)
plt.clf()
plt.plot(np.fromiter((-_.dPhi_dw[64] for _ in spec),dtype=np.float32)-np.arange(len(spec))*f.hop_size *2 * np.pi / f.frame_size)
plt.plot(np.fromiter((-_.dPhi_dw[64]* 2*np.pi/f.frame_size for _ in spec),dtype=np.float32)-np.arange(len(spec))*f.hop_size )
plt.clf()
plt.plot(np.fromiter((-_.dPhi_dw[64]* 2*np.pi/f.frame_size for _ in spec),dtype=np.float32)-np.arange(len(spec))*f.hop_size )
plt.plot(np.fromiter((-_.dPhi_dw[64]* 2*np.pi/f.frame_size for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size )
plt.clf()
plt.plot(np.fromiter((-_.dPhi_dw[64]* 2*np.pi/f.frame_size for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size )
plt.clf()
plt.plot(np.fromiter((-_.dPhi_dw[64]/( 2*np.pi/f.frame_size) for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size )
plt.plot(np.fromiter((-_.dPhi_dw[64]/( 2*np.pi/f.frame_size) for _ in spec),dtype=np.float32)-np.arange(len(spec))*f.hop_size )
plt.clf()
plt.plot(np.fromiter((_.dPhi_dw[64]/( 2*np.pi/f.frame_size) for _ in spec),dtype=np.float32)-np.arange(len(spec))*f.hop_size )
plt.clf()
plt.plot(np.fromiter((_.dPhi_dw[64]/( 2*np.pi/f.frame_size) for _ in spec),dtype=np.float32)-np.arange(len(spec))*f.hop_size)
plt.plot(np.fromiter((_.dPhi_dw[64]/( 2*np.pi/f.frame_size) for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size)
plt.plot(np.fromiter((_.dPhi_dw[64]*( 2*np.pi/f.frame_size) for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size)
plt.clf()
plt.plot(np.fromiter((_.dPhi_dw[64]*( 2*np.pi/f.frame_size) for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size)
plt.plot(np.fromiter((_.dPhi_dw[64] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size)
plt.clf()
plt.plot(np.fromiter((_.dPhi_dw[64] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size)
plt.plot(np.fromiter((_.dPhi_dw[72] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size)
plt.plot(np.fromiter((_.dPhi_dw[16] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size)
plt.plot(np.fromiter((_.dPhi_dw[128] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size)
plt.clf()
plt.plot(np.fromiter((_.dPhi_dw[128] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size*2)
plt.plot(np.fromiter((_.dPhi_dw[256] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size*2)
plt.plot(np.fromiter((_.dPhi_dw[256] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size)
plt.clf()
plt.plot(np.fromiter((_.dPhi_dw[256] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size)
do_one = lambda i: plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size) + i * f.hop_size
do_one(32)
do_one = lambda i: plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size + i * f.hop_size)
do_one(32)
plt.clf()
do_one(32)
do_one(33)
do_one(34)
do_one(35)
do_one = lambda i: plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size + i * f.frame_size)
do_one(34)
plt.clf()
do_one(34)
do_one(35)
do_one(36)
do_one(37)
do_one(38)
do_one(39)
do_one(40)
do_one(50)
do_one(60)
do_one = lambda i: plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size + i * f.hop_size * 2)
do_one(50)
plt.clf()
map(do_one,range(64,1024,64))
list(map(do_one,range(64,1024,64)))
do_one = lambda i: plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size + i )
list(map(do_one,range(64,1024,f.hop_size)))
plt.clf()
list(map(do_one,range(64,1024,f.hop_size)))
list(map(do_one,range(64,1024,16)))
plt.clf()
list(map(do_one,range(64,1024,16)))
list(map(do_one,range(64,1024,64)))
plt.clf()
list(map(do_one,range(64,1024,64)))
do_one = lambda i: plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+np.arange(len(spec))*f.hop_size + i *8)
plt.clf()
list(map(do_one,range(64,1024,64)))
do_one = lambda i: plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+ i *8)
list(map(do_one,range(64,1024,64)))
plt.clf()
list(map(do_one,range(64,1024,64)))
do_one = lambda i: (plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+ i *8),plt.plot([i*8]*r.coef))
list(map(do_one,range(64,1024,64)))
plt.clf()
do_one = lambda i: (plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+ i *8),plt.plot([i*8]*len(spec)))
list(map(do_one,range(64,1024,64)))
spec+=list(r.process(next(f)) for i in range(64))
list(map(do_one,range(64,1024,64)))
list(map(do_one,range(64,1024,16)))
plt.clf()
list(map(do_one,range(64,1024,16)))
do_one = lambda i: (plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+ i *8),plt.plot([i*32]*len(spec)))
list(map(do_one,range(64,1024,16)))
plt.clf()
list(map(do_one,range(64,1024,16)))
do_one = lambda i: (plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+ i *32),plt.plot([i*32]*len(spec)))
plt.clf()
list(map(do_one,range(64,1024,16)))
do_one = lambda i: (plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+ i *64),plt.plot([i*64]*len(spec)))
plt.clf()
list(map(do_one,range(64,1024,16)))
r=rmwarp.RMFFT(win=ss.kaiser(2048,12.sym=True));f = rmwarp.framer.NpFramer('/home/zen/Music/Chase & Status - Loader-8XsojGZ8tps.mp3',frame_size=r.size,hop_size=256,layout='mono');
r=rmwarp.RMFFT(win=ss.kaiser(2048,12.,sym=True));f = rmwarp.framer.NpFramer('/home/zen/Music/Chase & Status - Loader-8XsojGZ8tps.mp3',frame_size=r.size,hop_size=256,layout='mono');
f.seek(128.)
F=next(_ for _ in f if _.std() >= 0.2)
spec.clear()
spec+=list(r.process(next(f)) for i in range(64))
list(map(do_one,range(64,1024,16)))
plt.clf()
list(map(do_one,range(64,1024,16)))
r=rmwarp.RMFFT(win=ss.kaiser(2048,12.,sym=True));f = rmwarp.framer.NpFramer('/home/zen/Music/Chase & Status - Loader-8XsojGZ8tps.mp3',frame_size=r.size,hop_size=32,layout='mono');
plt.clf()
f.seek(128.)
F=next(_ for _ in f if _.std() >= 0.2)
spec+=list(r.process(next(f)) for i in range(256))
list(map(do_one,range(64,1024,16)))
spec.clear()
spec+=list(r.process(next(f)) for i in range(256))
list(map(do_one,range(64,1024,16)))
plt.clf()
list(map(do_one,range(64,1024,16)))
r=rmwarp.RMFFT(win=ss.kaiser(1024,12.,sym=True));f = rmwarp.framer.NpFramer('/home/zen/Music/Chase & Status - Loader-8XsojGZ8tps.mp3',frame_size=r.size,hop_size=32,layout='mono');
plt.clf()
spec.clear()
f.seek(128.)
F=next(_ for _ in f if _.std() >= 0.2)
list(map(do_one,range(64,1024,16)))
plt.clf()
spec+=list(r.process(next(f)) for i in range(256))
list(map(do_one,range(64,1024,16)))
list(map(do_one,range(64,512,16)))
plt.clf()
list(map(do_one,range(64,512,16)))
list(map(do_one,range(64,512,2)))
plt.clf()
list(map(do_one,range(64,512,4)))
list(map(do_one,range(64,128,1)))
plt.clf()
list(map(do_one,range(64,128,1)))
plt.clf()
do_one = lambda i: (plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+ i *256),plt.plot([i*256]*len(spec)))
list(map(do_one,range(64,128,1)))
do_one = lambda i: (plt.plot(np.fromiter((_.dPhi_dw[i] for _ in spec),dtype=np.float32)+ i *256),plt.plot([i*256]*len(spec)))ls
get_ipython().magic('ls ')
doit2 = lambda i:(plt.plot(((spec[i].dPhi_dw) - spec[i-1].dPhi_dw) +f.frame_size*i),plt.plot([f.frame_size * i]*r.coef),plt.plot([f.hop_size + f.frame_size * i]*r.coef))
plt.clf()
doit2 = lambda i:(plt.plot(((spec[i].dPhi_dw) - spec[i-1].dPhi_dw) +f.frame_size*i),plt.plot([f.frame_size * i]*r.coef),plt.plot([f.hop_size + f.frame_size * i]*r.coef))
list(map(doit2,range(1,len(spec))))
doit2 = lambda i:(plt.plot(princarg((spec[i].dPhi_dw) - spec[i-1].dPhi_dw) +f.frame_size*i),plt.plot([f.frame_size * i]*r.coef),plt.plot([f.hop_size + f.frame_size * i]*r.coef))
plt.clf()
list(map(doit2,range(1,len(spec))))
doit2 = lambda i:(plt.plot((spec[i].dPhi_dw - spec[i-1].dPhi_dw) +f.frame_size*i),plt.plot([f.frame_size * i]*r.coef),plt.plot([f.hop_size + f.frame_size * i]*r.coef))
spec.clear()
plt.clf()
spec+=list(r.process(next(f)) for i in range(32))
list(map(doit2,range(1,len(spec))))
plt.clf()
get_ipython().magic('ls ')
get_ipython().magic('save -a ./rm_session.py 200-')
